### ISSUE TITLE
Translation XXX not found for locale "zhCN"

### ISSUE THREAD

**Issue by WayneSunJazz** [laytya/Spy-vanilla#11]
I play 1.12 Chinese interface。 Everytime I logon game. SPY show this error message:
<img width="831" alt="截屏2022-12-15 17 16 56" src="https://user-images.githubusercontent.com/119514624/207821509-29ec9449-f308-42e8-a148-95665136b226.png">

I'm not asking for chinesizition，could you remove this error?

oh besides, SPY reminds everytime when detecate friendly‘s stealth。 Maybe we only want to detecate hostile‘s。

Thanks for your work done!

**Comment by shikulja** [comment]
To quickly fix the error, you can replace this library with a more complete one:
https://github.com/laytya/LibBabble-Spell-3.0

In the one that is now, spells are not available for all languages

**Comment by WayneSunJazz** [comment]
> To quickly fix the error, you can replace this library with a more complete one: https://github.com/laytya/LibBabble-Spell-3.0
> 
> In the one that is now, spells are not available for all languages

Thank you , I will try it.
