### ISSUE TITLE
causes issues when using other Addons for Macros

### ISSUE THREAD

**Issue by Evyn97** [laytya/Spy-vanilla#15]
I'm using RoidMacros and when I activate the Spy addon it makes the "#showtooltip" type in the say chat everytime I click an ability with "#showtooltip" it's quite frustrating

Edit: using RoidMacros and CleverMacro seems to fix the issue for now

**Comment by Faalvare** [comment]
happens to me too, but using roidmacros + clevermacro doesn't work for me

**Comment by laytya** [comment]
dont use #showtooltip in macroses.
