### ISSUE TITLE
BackPorting Spy_KOSReasonList 

### ISSUE THREAD

**Issue by shikulja** [laytya/Spy-vanilla#2]
SpyTBCv2.0.7 Has a newer list of reasons, 

you can transfer localizations from there
(it’s better to just comment out unnecessary lines, so it’s better to compare and transfer the translation to other languages ​​later)

**Comment by laytya** [comment]
У меня есть переводы все с ретейла - я просто не делал их еще. Как добавлю - Вычитаешь и поправим
