### ISSUE TITLE
Loc typos

### ISSUE THREAD

**Issue by shikulja** [laytya/Spy-vanilla#3]
Некоторые кнопки в статистике не переведены

<img width="459" alt="image" src="https://user-images.githubusercontent.com/3386359/200813756-8f519684-f1d7-4daf-8f57-05113eb75612.png">

--Stats
L["Won"] = "Побед" --
L["Lost"] = "Поражений" --
L["Reason"] = "Причина" --

----Возможно они не нужны? я их не нашел. Надо проверить
L["Realm"] = "Realm" 
L["HonorKills"] = "Почетные убийства"
L["PvPDeaths"] = "Смерти в PvP"

**Comment by shikulja** [comment]
/spy config
<img width="236" alt="image" src="https://user-images.githubusercontent.com/3386359/200819039-8a9dbf2e-df30-4533-8968-044ab695f5ac.png">

**Comment by shikulja** [comment]
в настройках display. Проверь на английской локали. Похоже ошибка
<img width="327" alt="image" src="https://user-images.githubusercontent.com/3386359/200819784-58cb8023-e59a-427a-a498-5aafd84b4346.png">

**Comment by laytya** [comment]
> в настройках display. Проверь на английской локали. Похоже ошибка
>
не - это шаредмедия виджеты - я ж проверял - все работает

**Comment by laytya** [comment]
> /spy config

это переводится в библиотеке Ace3 - пока не трогай

**Comment by shikulja** [comment]
> > /spy config
> 
> это переводится в библиотеке Ace3 - пока не трогай

@laytya Конфиг заголовка окна (на скрине), его потом можно будет добавить.
Просто написал как найти - /spy config > display

**Comment by laytya** [comment]
> @laytya Конфиг заголовка окна (на скрине), его потом можно будет добавить.
> Просто написал как найти - /spy config > display

да я знаю... это окно общее для всех конфигураций аддонов на асе3 - замена стандартному близовскому

**Comment by shikulja** [comment]
StaticPopupDialogs в локалях отличается в последней версии, впрочем и в этой и в новой, у меня выскакивала ошибка
<img width="536" alt="image" src="https://user-images.githubusercontent.com/3386359/200898383-de8e499f-3e93-48a0-b846-d99a345bda0a.png">

Возникает при добавлении ручных заметок

**Comment by laytya** [comment]
скинь что там у тя по НПС было

**Comment by shikulja** [comment]
@laytya По каким нпц?

**Comment by laytya** [comment]
я баблспел добавил руские спелы
можно пробовать локаль натягивать

**Comment by laytya** [comment]
Скинь локаль я задифаю ее

**Comment by shikulja** [comment]
[Spy.zip](https://github.com/laytya/Spy-vanilla/files/10010627/Spy.zip)
@laytya ну особо там отличий не много.
Пока занимаюсь бабл спелл, полную базу готовлю на всех локалях, но это не быстро

**Comment by laytya** [comment]
Проверяй ру локаль

https://github.com/laytya/Spy-vanilla/releases/tag/beta0.3.5

**Comment by shikulja** [comment]
@laytya 
		-- spells from spy addon  TBC?
		["Aspect of the Viper"] = true,
		["The Beast Within"] = true,
		["Steady Shot"] = true,
		["Dragon's Breath"] = true,
		["Righteous Defense"] = true,
		["Spiritual Attunement"] = true,
		["Divine Illumination"] = true,
		["Avenger's Shield"] = true,
		["Circle of Healing"] = true,
		["Pain Suppression"] = true,
		["Vampiric Touch"] = true,
		["Water Shield"] = true,
		["Totem of Wrath"] = true,
		["Shamanistic Rage"] = true,
		["Earth Shield"] = true,
		["Backlash"] = true,
		["Summon Felguard"] = true,
		["Unstable Affliction"] = true,
		["Shadowfury"] = true,

**Comment by shikulja** [comment]
@laytya 

[WORKDIR_BubbleSpell_v2.zip](https://github.com/laytya/Spy-vanilla/files/10016809/WORKDIR_BubbleSpell_v2.zip)
[LibBabble-Spell-3.0.zip](https://github.com/laytya/Spy-vanilla/files/10014176/LibBabble-Spell-3.0.zip)

Допиливать не буду, сделал для удобства.
esMX не нашел, надо выдирать с клиента
ptBR неофициальный, есть в vmangos repack *github)

Двойные кавычки "spell "Spell"" разбил слешами, но по идее надо было автозаменой тильдами в экселе, или ручками (выписал имена спеллов в тхт)

iconspell 
["Magic Dust"] = "Inv_misc_dust_02", хоть и есть в ванилле, но это предмет, а не спелл (добавлен для удобства?)...
Таблицу всех иконок для спеллов есть, но не добавил в баблспелл, хз как сопоставлять "Имя спелла" и "Иконку", надо формулу придумать

а.. еще некоторые языки например de, fr, используют замену букв-символьными кодами. Я этого не делал, мб и так норм, а если нет курить доки, по языковым символам мне лень и хз где курить такое

**Comment by shikulja** [comment]
@laytya цветные классы пропали в статистике, надо добавить classcolour
не знаю. но hp по идее должно в основном окне "вокруг", уменьшатся

**Comment by laytya** [comment]
> не знаю. но hp по идее должно в основном окне "вокруг", уменьшатся

это сделать не реально на ванилле - если делать через месаджи аддонов лагать будет короче та еще задачка

**Comment by laytya** [comment]
> @laytya -- spells from spy addon TBC? ["Aspect of the Viper"] = true, ["The Beast Within"] = true, ["Steady Shot"] = true, ["Dragon's Breath"] = true, ["Righteous Defense"] = true, ["Spiritual Attunement"] = true, ["Divine Illumination"] = true, 

да это пережиток библиотеки с ТБС =) можно вычищать

**Comment by laytya** [comment]
> @laytya
> 
> [WORKDIR_BubbleSpell_v2.zip](https://github.com/laytya/Spy-vanilla/files/10016809/WORKDIR_BubbleSpell_v2.zip) [LibBabble-Spell-3.0.zip](https://github.com/laytya/Spy-vanilla/files/10014176/LibBabble-Spell-3.0.zip)

ппц объем получается - возможно это не стоит того.... и там куча спелов которые не используются

покачто нада сделать соответствие тому что есть на англ локали у меня а потом думать про добавление всего этого

**Comment by laytya** [comment]
В Спае я спелы с ТБС предварительно почистил - их нада с баблспела тоже почистить

**Comment by shikulja** [comment]
@laytya в 0.3.7 на спеллы TBC - Spy все ещё ругался поэтому пока, оставил.
Вычистить и урезать можно. Есть Spell id category, по идее по ней можно вычистить старые спеллы и другие не нужные. Но описание флагов этой таблицы не нашел.
Потом можно сверить и добавить из BS2.2 2.3 что осталось с помощью winmerge\Beyond Compare
Для меня пока проблема назначить иконки, заклинаниям.

**Comment by shikulja** [comment]
<img width="331" alt="Снимок экрана_20221116_213722" src="https://user-images.githubusercontent.com/3386359/202265041-beb2924a-7e6f-4c17-b6f2-d034b824974e.png">
<img width="775" alt="Снимок экрана_20221116_214201" src="https://user-images.githubusercontent.com/3386359/202265847-1297bff3-483f-4e7c-a382-916b416871e1.png">

С большой

**Comment by shikulja** [comment]
<img width="258" alt="Снимок экрана_20221116_214421" src="https://user-images.githubusercontent.com/3386359/202266279-cba99068-4127-43ca-97f4-ca31f47d4633.png">
<img width="821" alt="Снимок экрана_20221116_214739" src="https://user-images.githubusercontent.com/3386359/202266949-2f99ac17-bd14-4dfb-af19-f4a7c1cc5821.png">
фрейме-в подсказке>кадре.  Правильно "в окне, или рамке"

<img width="718" alt="Снимок экрана_20221116_214910" src="https://user-images.githubusercontent.com/3386359/202267304-99650b39-3928-4ed0-b648-99559c1bbfd5.png">
тоже самое целевые кадры


<img width="236" alt="Снимок экрана_20221116_215051" src="https://user-images.githubusercontent.com/3386359/202267656-f2791502-6bb8-4a4a-9d86-436b31c267b9.png">
лимит а не предел.


<img width="298" alt="Снимок экрана_20221116_215250" src="https://user-images.githubusercontent.com/3386359/202268126-41f1ea0f-70d7-4d05-8fa6-da8fcbe2a22d.png">

Транслита тут очень много, вычитывать с 0

**Comment by shikulja** [comment]
<img width="247" alt="Снимок экрана_20221116_215659" src="https://user-images.githubusercontent.com/3386359/202268876-5f84850b-a06f-4e27-b453-00c76a526dec.png">
расширить кнопку

**Comment by shikulja** [comment]
<img width="741" alt="Снимок экрана_20221116_215805" src="https://user-images.githubusercontent.com/3386359/202269111-636ec530-dc12-44f2-92ec-733fb6a017bb.png">
Отправить сообщениЕ
ГруппЕ-ГильдиИ-РейдУ

<img width="233" alt="Снимок экрана_20221116_215916" src="https://user-images.githubusercontent.com/3386359/202269324-f186cea4-088a-4094-82ee-46af1cae8757.png">
По умолчанию. Ошибка окна(рамки).  подвижной я хз, в моем переводе можно подсмотреть

**Comment by shikulja** [comment]
<img width="386" alt="Снимок экрана_20221116_221303" src="https://user-images.githubusercontent.com/3386359/202271942-2f22de93-30f3-4a25-b89f-8225202a8c51.png">
Аддон SPY включЁн\выключен
Перевернуть надо

**Comment by shikulja** [comment]
L["LocalDefenseChannelName"] = "ОборонаЛокальный" 

<img width="124" alt="Снимок экрана_20221116_221724" src="https://user-images.githubusercontent.com/3386359/202273761-f89d9d9a-62a4-4804-b417-24f94ee0dbbf.png">
на элизиуме английский канал, мб и на других серверах.. смотреть надо.

**Comment by shikulja** [comment]
--++ Class descriptions
L["UNKNOWN"] = "Неизвестный"
L["DRUID"] = "Друид"
L["HUNTER"] = "Охотник"
L["MAGE"] = "Маг"
L["PALADIN"] = "Паладин"
L["PRIEST"] = "Жрец"
L["ROGUE"] = "Разбойник"
L["SHAMAN"] = "Шаман"
L["WARLOCK"] = "Чернокнижник"
L["WARRIOR"] = "Воин"
поменяй на, чтобы классы цветные были
L["UNKNOWN"] = "|cff191919Неизвестный|cffffffff"
L["DRUID"] = "|cffff7c0aДруид|cffffffff"
L["HUNTER"] = "|cffaad372Охотник|cffffffff"
L["MAGE"] = "|cff68ccefМаг|cffffffff"
L["PALADIN"] = "|cfff48cbaПаладин|cffffffff"
L["PRIEST"] = "|cffffffffЖрец|cffffffff"
L["ROGUE"] = "|cfffff468Разбойник|cffffffff"
L["SHAMAN"] = "|cff2359ffШаман|cffffffff"
L["WARLOCK"] = "|cff9382c9Чернокнижник|cffffffff"
L["WARRIOR"] = "|cffc69b6dВоин|cffffffff"

**Comment by shikulja** [comment]
- Добавил все иконки, в том числе остатки от старых BS(106шт.) 
- Удалил иконки "Test"
- Добавил остатки заклинаний от старых BS (87шт. устаревших, 2шт. предмета, 8шт. хз откуда)
- Добавил notes ruru в toc
- Отсортировал по алфавиту
- мб еще что нибудь. перебрал перепроверил.
- перевод 2 предметов на остальные языки

**Comment by shikulja** [comment]
> в настройках display. Проверь на английской локали. Похоже ошибка <img alt="image" width="327" src="https://user-images.githubusercontent.com/3386359/200819784-58cb8023-e59a-427a-a498-5aafd84b4346.png">



> > в настройках display. Проверь на английской локали. Похоже ошибка
> 
> не - это шаредмедия виджеты - я ж проверял - все работает

Моя ошибка. Слишком низкий приоритет для AceLibrary

**Comment by shikulja** [comment]
[LibBabble-Spell-3.0_V3.zip](https://github.com/laytya/Spy-vanilla/files/10056980/LibBabble-Spell-3.0_V3.zip)
[WORKDIR_BubbleSpell_v4.zip](https://github.com/laytya/Spy-vanilla/files/10056981/WORKDIR_BubbleSpell_v4.zip)

Ексель пересобран, переводы взяты с парсера получше, динамические ссылки на основную таблицу, почищен.
Добавил костыль  для заклинания Riposte. Имеет индекс иконки 0. Такого индекса в клиенте нет. Теперь будет.

BS почистил от старых иконок.. часть дубликаты, около 5 с опечатками, большая часть устаревших иконок,
и часть иконок заккоментировал, их иконки не соответствуют, но мало ли.. может так и задумано, или ошиблись и вместо спелла взяли иконку от итема.

Скорее всего это финиш

**Comment by laytya** [comment]
Создал для LibBabble-Spell-3.0 отдельный репозиторий. https://github.com/laytya/LibBabble-Spell-3.0

**Comment by laytya** [comment]
Ру локаль для спая сам накатишь? или мне делать?

**Comment by shikulja** [comment]
делай, я потом вычитать помогу.
С бабл спелл хорошо, что есть полная версия, но его еще надо досмотреть.
Скорее всего разбить слешами 'Trelane\\'s Freezing Touch' такие спеллы.
И возможно подчистить, так как есть одинаковые заклинания,  с разной иконкой
Но мне пока и так сойдет, буду пользоваться

**Comment by shikulja** [comment]
@laytya 
в BC3.0
для всех локалей
	lib:SetCurrentTranslations {
		Warlock = "Чернокнижник",
		Warrior = "Воин",
		Hunter = "Охотник",
		Mage = "Маг",
		Priest = "Жрец",
		Druid = "Друид",
		Paladin = "Паладин",
		Shaman = "Шаман",
		Rogue = "Разбойник",

обычно везде как обычно
		["Warlock"] = "Чернокнижник",
		["Warrior"] = "Воин",
		["Hunter"] = "Охотник",
		["Mage"] = "Маг",
		["Priest"] = "Жрец",
		["Druid"] = "Друид",
		["Paladin"] = "Паладин",
		["Shaman"] = "Шаман",
		["Rogue"] = "Разбойник",

или это так задумано?

**Comment by laytya** [comment]
это одно и тоже по сути

**Comment by shikulja** [comment]
@laytya
подключил AceLocale-3.0 к своему проекту работает отлично, а вот BC3, если прописать в локал, крашит клиент. 
потом буду думать, может зависимостей не хватает.
Может дашь контакты для телеги или вк, чтобы не мусорить гит?

include("libs\\LibStub\\LibStub.lua");

include("libs\\CallbackHandler-1.0\\CallbackHandler-1.0.lua");
include("libs\\Ace3v\\AceLocale-3.0\\AceLocale-3.0.lua");
include("libs\\Ace3v\\AceLocale-3.1\\AceLocale-3.1.lua");


--include("libs\\LibBabble-Class-3.0\\LibBabble-3.0.lua");
--include("libs\\LibBabble-Class-3.0\\LibBabble-Class-3.0.lua");

include("locales\\Locale_enUS.lua");
include("locales\\Locale_ruRU.lua");

	--local BC = LibStub("LibBabble-Class-3.0")
	local L = LibStub("AceLocale-3.0"):GetLocale("oGasai");

**Comment by laytya** [comment]
В дискорде Everlooka меня найди

**Comment by shikulja** [comment]
@laytya 
<img width="420" alt="image" src="https://user-images.githubusercontent.com/3386359/203966997-4f98d5f0-43c3-42f3-b59a-64699d5a92ab.png">

**Comment by laytya** [comment]
https://discord.gg/everlook
@LaYt
