### ISSUE TITLE
Spy_AbilityList

### ISSUE THREAD

**Issue by shikulja** [laytya/Spy-vanilla#4]
Переводить? или ты прикрутишь BS\BC\BR позже?

**Comment by laytya** [comment]
Да можешь BS прикручивать -  я сделал новый Bablespell - погляди кстати - очень много добавил - но я брал с вовхеда - не знаю на скоко там правильно переведено с ру ванилой
Новый Баблеспелл портирован и не завязан на АсеЛокале
