### ISSUE TITLE
Заметки.

### ISSUE THREAD

**Issue by Valeriy-Semenkov** [laytya/Spy-vanilla#6]
Не знал куда отписать, решил отписать тут, извините, если мимо.
Побегал пару дней с аддоном, использовав его как на офе, то есть, просто открытое окно, анонсы звуком, анонсы стелса.
 В целом то, что он уже просто работает - чудо.
 Теперь то, что я подметил:
1. Аддон периодически срабатывает на союзников, и пока ты не прокликаешь таргеты которые он нашел - не будешь уверен, нашел ли он союзника или врага.
2.  Обнаружение стелса , очень похоже, что не работает , проверял только с товарищем в дуэли, аддон срабатывал на выходе из стелса, но вот когда он входил в стелс, даже будучи в моем таргете, аддон не обращал внимания на это.
3. При команде /reload у меня пропадает окно аддона, при этом звук анонсов остается, помогает только релогин в игру, до первого же релоада интерфейса.
Возможно я дурак, и что то сделал не так, в настройки почти не залазил, ну и не трогал там ничего толком, на офе все и так работало.
Если необходимы скриншоты или какие либо записи, готов сделать. Ошибок в чате, при обычной работе аддон никаких не показал, но возможно, их скрывает мой pfui.

**Comment by shikulja** [comment]
@Valeriy-Semenkov 
у вас русский клиент?

**Comment by Valeriy-Semenkov** [comment]
@shikulja 
Да, вот сейчас пересяду на английский, буду с него тоже смотреть, как работает аддон.

**Comment by shikulja** [comment]
@Valeriy-Semenkov 
1. если клиент русский, то определение, расс\классов будет работать не корректно, до добавления локализации аддона.
Это может влиять и на неправильное обнаружение врагов\союзников
2. в русском клиенте стелс не будет работать корректно, так как не готова локализация заклинаний. Нужно подождать релиза. Пока только для тестов.
3. после /reload у меня окно не пропадало. Но всё же он может отключиться поэтому попробуйте /spy show

**Comment by Valeriy-Semenkov** [comment]
@shikulja Плохо написал, spy show и прочие команды не работают, теперь подозреваю что из-за клиента, в чате аддон отзывается, но окна нет.

**Comment by Valeriy-Semenkov** [comment]
В целом, я понял, спасибо, буду ждать локализацию, не люблю играть на английском, как то не комфортно.

**Comment by laytya** [comment]
1. определение врагов по комбат логу еще в стадии отладки. Такчто просто прожмайте пока бары
2. Стелс будет детектится токо выход с него это особенность Ванилы и ничего с этим не сделать
3. Это я проверю - возможно чтото с управлением настройкой - рекомендую поставить FuBar - появится кнопка управления аддоном.

проверьте нет ли ошибок при Релоаде?

**Comment by Valeriy-Semenkov** [comment]
@laytya  Поставил только что FuBar , проверил, ошибка осталась , по нажатию на кнопку происходит все то же самое, что и при текстовой команде, в чате аддон отзывается, звук есть, панели нет. Однако, кнопка reset помогает , панель снова появляется, то есть перезаходить уже не нужно будет. Спасибо.

**Comment by Valeriy-Semenkov** [comment]
Команда /Spy reset в чате привела к такой ошибке 
![image](https://user-images.githubusercontent.com/79516642/201589251-89fef546-51f8-44d2-b0b1-592f8d403507.png)

**Comment by laytya** [comment]
Reset пофиксил = про пропажу окна не понятно - поройтесь в настройках там есть много галочек для разных ситуаций - например вырубать спай в определенных местах или когда флаг пвп выключен
Пока не смог воспроизвести вашу ситуацию - у меня все работает после релоада

**Comment by Valeriy-Semenkov** [comment]
@laytya  Да, галочки видел, я выключил их все, чтобы он вообще никогда не пропадал, я попробую разобраться, что заставляет его выключаться, отпишу, если пойму.  У меня помимо руссика еще патч на дальность неймплейтов, нормальный фов и все такое, может из-за него что то не так работает.

**Comment by Valeriy-Semenkov** [comment]
Отключил все аддоны на клиенте, запустил только со спаем, вот такая ошибка сходу. 
![image](https://user-images.githubusercontent.com/79516642/201634704-46ee1f09-e902-48c5-81af-045cd299700f.png)

**Comment by Valeriy-Semenkov** [comment]
Вообщем, проверил слегка, отключил все аддоны, панель не исчезала, с включенным  только pfui и спай панель пропадает при reload. в чате вот такие ошибки 
![image](https://user-images.githubusercontent.com/79516642/201635963-bb8d5c66-9f9b-494e-b6bf-6885052edbea.png)

**Comment by laytya** [comment]
это Ру локализация не полная погоди поправим.

**Comment by Valeriy-Semenkov** [comment]
Если вкратце. Товарищ играет без pfUI , у него бага с пропажей панели после команды /reload нет, значит конфликт между аддонами какой-то. Эта проблема решаема? Ошибок никаких не находил, кроме тех, что выше.

**Comment by laytya** [comment]
> Команда /Spy reset в чате привела к такой ошибке ![image](https://user-images.githubusercontent.com/79516642/201589251-89fef546-51f8-44d2-b0b1-592f8d403507.png)

Fixed in https://github.com/laytya/Spy-vanilla/releases/tag/beta0.3.5

**Comment by laytya** [comment]
> Отключил все аддоны на клиенте, запустил только со спаем, вот такая ошибка сходу. ![image](https://user-images.githubusercontent.com/79516642/201634704-46ee1f09-e902-48c5-81af-045cd299700f.png)

Fixed in https://github.com/laytya/Spy-vanilla/releases/tag/beta0.3.5

**Comment by laytya** [comment]
Проверяйте Релоад

**Comment by Valeriy-Semenkov** [comment]
@laytya  Проверил, у меня она по прежнему пропадает, но у друга на английском клиенте с pfui все остается после /reload , видимо проблема с моей стороны, буду пытаться разобраться, появилось подозрение, что при релоаде панель спая съезжает куда-то за пределы экрана, и вот в этом то и проблема, играю на 2 к мониторе, в 2к разрешение в окне без рамок. Спасибо огромное за такие быстрые фиксы, и ру локализацию, очень круто!

**Comment by Valeriy-Semenkov** [comment]
@laytya  Все, кажется я выяснил в чем проблема. В pfUI у меня включено масштабирование интерфейса , у друга нет, как только я его отключил, панель перестала съезжать после /reload.

**Comment by gl00m3r** [comment]
Спрошу здесь, чтобы новый не открывать.

А зачем собственно аддон использует библиотеки для отслеживания кулдауна, диминишинга способностей? Не лишний ли данный функционал?

**Comment by laytya** [comment]
это задел на будущий функционал.
