### ISSUE TITLE
Lua error

### ISSUE THREAD

**Issue by Valeriy-Semenkov** [laytya/Spy-vanilla#7]
Поставил новую версию (beta 0.3.8)  , предварительно полностью вычистил старую ( включая профили из папки WTF) , постоянный спам такой ошибки  
![image](https://user-images.githubusercontent.com/79516642/202797579-f78cc50b-5b33-4105-991d-3f6dbaef999f.png)

**Comment by laytya** [comment]
Redownload SPY - fixed
